# Generated by Django 3.2.5 on 2022-09-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq_settings', '0002_auto_20220906_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq_qatranslation',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='search_views', to='faq_settings.IpModel'),
        ),
    ]
