# Generated by Django 3.2.5 on 2022-09-13 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq_settings', '0004_auto_20220909_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq_qatranslation',
            name='views',
        ),
        migrations.DeleteModel(
            name='IpModel',
        ),
    ]
