# Generated by Django 3.2.5 on 2022-09-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq_settings', '0006_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='faq_qatranslation',
            name='SEO_Keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='faq_qatranslation',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='faq_views', to='faq_settings.IpModel'),
        ),
    ]
