# Generated by Django 3.2.5 on 2022-09-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq_settings', '0007_auto_20220916_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user',
            field=models.TextField(default=None, max_length='256'),
        ),
    ]
