# Generated by Django 3.2.5 on 2022-09-01 13:55

from django.db import migrations
import django.db.models.deletion
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_detail_course_detailtranslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_detailtranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations21', to='course.course_detail'),
        ),
    ]
