# Generated by Django 3.2.5 on 2022-09-02 06:56

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_test01_test01translation_test02_test02translation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CategoryTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('category_Title', models.CharField(max_length=500)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='course.category')),
            ],
            options={
                'verbose_name': 'category Translation',
                'db_table': 'course_category_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases = (parler.models.TranslatableModel, models.Model),
        ),
        migrations.CreateModel(
            name='Faq_QA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Faq_QATranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('question_Title', models.CharField(max_length=500)),
                ('question_Description', models.TextField()),
                ('SEO_Keywords', models.TextField()),
                ('category_Option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.category')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='course.faq_qa')),
            ],
            options={
                'verbose_name': 'faq_qa Translation',
                'db_table': 'course_faq_qa_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases = (parler.models.TranslatableModel, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='course_detailtranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='course_detailtranslation',
            name='master',
        ),
        migrations.AlterUniqueTogether(
            name='course_feetranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='course_feetranslation',
            name='master',
        ),
        migrations.AlterUniqueTogether(
            name='coursetranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='coursetranslation',
            name='master',
        ),
        migrations.AlterUniqueTogether(
            name='test01translation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='test01translation',
            name='master',
        ),
        migrations.AlterUniqueTogether(
            name='test02translation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='test02translation',
            name='master',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Course_detail',
        ),
        migrations.DeleteModel(
            name='Course_detailTranslation',
        ),
        migrations.DeleteModel(
            name='Course_Fee',
        ),
        migrations.DeleteModel(
            name='Course_FeeTranslation',
        ),
        migrations.DeleteModel(
            name='CourseTranslation',
        ),
        migrations.DeleteModel(
            name='Test01',
        ),
        migrations.DeleteModel(
            name='Test01Translation',
        ),
        migrations.DeleteModel(
            name='Test02',
        ),
        migrations.DeleteModel(
            name='Test02Translation',
        ),
    ]
